# Generated by Django 4.2.3 on 2023-09-09 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supplement_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('Protein powders', 'Protein powders'), ('Creatine', 'Creatine'), ('Pre-Workouts', 'Pre-Workouts'), ('Post-Workouts', 'Post-Workouts'), ('Test Boosters', 'Test Boosters'), ('Vitamins and Minerals', 'Vitamins and Minerals'), ('Clothing', 'Clothing'), ('Workout Accessories', 'Workout Accessories')])),
                ('subcategory', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.PositiveIntegerField()),
                ('flavor', models.CharField(max_length=20)),
                ('is_new', models.BooleanField()),
                ('popularity', models.IntegerField()),
                ('main_image', models.ImageField(upload_to=supplement_store.models.item_image_upload_path)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=supplement_store.models.item_image_upload_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=supplement_store.models.item_image_upload_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=supplement_store.models.item_image_upload_path)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wishlisted', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement_store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_purchased', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement_store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement_store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=False)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement_store.item')),
            ],
        ),
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField()),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement_store.item')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('in_cart', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement_store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
