# Generated by Django 4.2.3 on 2023-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0002_item_user_address_user_birth_wishlist_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
