# Generated by Django 4.2.3 on 2023-09-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0004_coupon_item_is_on_sale_item_sale_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Protein powders', 'Protein powders'), ('Creatine', 'Creatine'), ('Pre-Workouts', 'Pre-Workouts'), ('Post-Workouts', 'Post-Workouts'), ('Test Boosters', 'Test Boosters'), ('Mass Gainers', 'Mass Gainers'), ('Weight Loss', 'Weight Loss'), ('Vitamins and Minerals', 'Vitamins and Minerals'), ('Meal Replacements', 'Meal Replacements'), ('Clothing', 'Clothing'), ('Workout Accessories', 'Workout Accessories')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='flavor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
