# Generated by Django 4.2.3 on 2023-09-21 14:48

from django.db import migrations, models
import supplement_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0007_slideshowimage_delete_slideshowimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowimage',
            name='image',
            field=models.ImageField(upload_to=supplement_store.models.slide_show_upload_path),
        ),
    ]
