# Generated by Django 4.2.3 on 2023-09-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0008_alter_slideshowimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowimage',
            name='actual_url',
            field=models.CharField(default='static/supplement_store/images/slide_show_images/2023-09-21_15-30-02_None'),
        ),
    ]
