# Generated by Django 4.2.3 on 2023-09-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0009_slideshowimage_actual_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshowimage',
            name='actual_url',
        ),
    ]
