# Generated by Django 4.2.3 on 2023-09-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0010_remove_slideshowimage_actual_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remember_me',
            field=models.BooleanField(default=True),
        ),
    ]
