# Generated by Django 4.2.3 on 2023-09-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0014_support_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=1000)),
                ('latest_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement_store.support')),
            ],
        ),
    ]
