# Generated by Django 4.2.3 on 2023-09-29 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0015_supportanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportanswer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='support',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
