# Generated by Django 4.2.3 on 2023-09-30 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0017_user_is_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportanswer',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
