# Generated by Django 4.2.3 on 2023-10-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0018_supportanswer_answered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('IronMaxx', 'IronMaxx'), ('OstroVit', 'OstroVit'), ('BioTechUSA', 'BioTechUSA'), ('AmiX', 'AmiX'), ('Myprotein', 'Myprotein'), ('BSN', 'BSN'), ('Optinum Nutrition', 'Optinum Nutrition'), ('Scitec Nutrition', 'Scitec Nutrition'), ('Gorilla Mind', 'Gorilla Mind'), ('HTLT', 'HTLT'), ('Quest Nutrition', 'Quest Nutrition'), ('Gymshark', 'Gymshark'), ('Under Armour', 'Under Armour'), ('Retaliation Project', 'Retaliation Project')]),
        ),
    ]
