# Generated by Django 4.2.3 on 2023-10-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0021_alter_item_image1_alter_item_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='InStock',
        ),
    ]
