# Generated by Django 4.2.3 on 2023-10-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0022_item_is_available_item_quantity_delete_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_review',
            field=models.DecimalField(blank=None, decimal_places=1, default=0, max_digits=1, null=None),
        ),
    ]
