# Generated by Django 4.2.3 on 2023-10-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0023_item_average_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='average_review',
            field=models.DecimalField(blank=None, decimal_places=1, default=0, max_digits=2, null=None),
        ),
    ]
