# Generated by Django 4.2.3 on 2023-10-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0024_alter_item_average_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='average_review',
        ),
    ]
