# Generated by Django 4.2.3 on 2023-10-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0025_remove_item_average_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
