# Generated by Django 4.2.3 on 2023-10-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0026_item_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='average_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
