# Generated by Django 4.2.3 on 2023-10-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0027_alter_item_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
