# Generated by Django 4.2.5 on 2023-12-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0028_alter_item_sale_end_date_alter_item_sale_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
