# Generated by Django 4.2.3 on 2024-02-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0028_alter_item_sale_end_date_alter_item_sale_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
