# Generated by Django 4.2.5 on 2024-10-08 21:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0030_alter_transaction_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_purchased',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement_store.item')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement_store.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ManyToManyField(through='supplement_store.TransactionItem', to='supplement_store.item'),
        ),
    ]
