# Generated by Django 5.1.6 on 2025-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0032_remove_item_is_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Protein powders', 'Protein powders'), ('Creatine', 'Creatine'), ('Pre-Workouts', 'Pre-Workouts'), ('Post-Workouts', 'Post-Workouts'), ('Amino Acids', 'Amino Acids'), ('Test Boosters', 'Test Boosters'), ('Mass Gainers', 'Mass Gainers'), ('Weight Loss', 'Weight Loss'), ('Vitamins and Minerals', 'Vitamins and Minerals'), ('Meal Replacements', 'Meal Replacements'), ('Clothing', 'Clothing'), ('Workout Accessories', 'Workout Accessories')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='flavor',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
