# Generated by Django 5.1.6 on 2025-03-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0034_alter_user_address_alter_user_birth_alter_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='is_wishlisted',
        ),
    ]
