# Generated by Django 5.1.6 on 2025-03-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0035_remove_wishlist_is_wishlisted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionItem',
        ),
    ]
