# Generated by Django 5.1.6 on 2025-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplement_store', '0041_alter_item_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='remember_me',
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('IronMaxx', 'IronMaxx'), ('OstroVit', 'OstroVit'), ('BioTechUSA', 'BioTechUSA'), ('AmiX', 'AmiX'), ('Myprotein', 'Myprotein'), ('BSN', 'BSN'), ('Optinum Nutrition', 'Optinum Nutrition'), ('Scitec Nutrition', 'Scitec Nutrition'), ('Gorilla Mind', 'Gorilla Mind'), ('HTLT', 'HTLT'), ('Quest Nutrition', 'Quest Nutrition')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Protein powders', 'Protein powders'), ('Creatine', 'Creatine'), ('Pre-Workouts', 'Pre-Workouts'), ('Post-Workouts', 'Post-Workouts'), ('Amino Acids', 'Amino Acids'), ('Test Boosters', 'Test Boosters'), ('Mass Gainers', 'Mass Gainers'), ('Weight Loss', 'Weight Loss'), ('Vitamins and Minerals', 'Vitamins and Minerals'), ('Meal Replacements', 'Meal Replacements')]),
        ),
    ]
